# Generated by Django 6.0.5 on 2026-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Facilities', 'Facilities'), ('Finance', 'Finance'), ('Administration', 'Administration'), ('General', 'General')], default='General', max_length=30),
        ),
    ]
