# Generated by Django 6.0.5 on 2026-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
