# Generated by Django 6.0.5 on 2026-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_escalated_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_hidden_from_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_hidden_from_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_hidden_from_user',
            field=models.BooleanField(default=False),
        ),
    ]
