# Generated by Django 6.0.5 on 2026-07-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_is_hidden_from_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
