# Generated by Django 6.0.5 on 2026-07-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_admin_hidden_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='admin_hidden_at',
            new_name='completed_at',
        ),
    ]
