# Generated by Django 6.0.5 on 2026-07-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_rename_admin_hidden_at_complaint_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hidden_from_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
